### ISSUE TITLE
Schema snapshot timeout error

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#1023]
```
Microsoft.SqlServer.Management.Smo.FailedOperationException: Prefetch objects failed for Database 'MyDatabase'. 
 ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
ClientConnectionId:cd27f931-90b8-48d6-9b3f-46759e372450
Error Number:-2,State:0,Class:11
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataReader(String query, SqlCommand& command)
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchObjects(ScriptingPreferences options, IEnumerable`1 filters)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchTables(ScriptingPreferences options, String tableFilter)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchTables(ScriptingPreferences options)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchObjectsImpl(Type objectType, ScriptingPreferences scriptingPreferences)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchObjectsImpl(Type objectType, ScriptingPreferences scriptingPreferences)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchObjects(Type objectType, ScriptingPreferences scriptingPreferences)
   at Microsoft.SqlServer.Management.Smo.Database.PrefetchObjects(Type objectType, ScriptingOptions scriptingOptions)
   at DBADash.SchemaSnapshotDB.AddTables(Database db, DataTable dtSchema) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 874
   at DBADash.SchemaSnapshotDB.SnapshotDB(String DBName, IErrorLogger errorLogger) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 257
   at DBADash.SchemaSnapshotDB.GenerateSchemaSnapshots(CollectionConfig Config, DBADashSource src) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 969
```

It looks like the timeout can be configured using:

`instance.ConnectionContext.StatementTimeout = 0`

The default is 600/10mins.  Ideally, this value is increased or is made configurable.

**Comment by DavidWiseman** [comment]
Timeout can now be configured:
https://dbadash.com/docs/help/query-timeout/

e.g.
```
{
  "CollectionCommandTimeouts": {
    "SchemaSnapshot": 0
  }
}
```

Included in 3.11 🚀
