### ISSUE TITLE
Schema snapshots fail on SQL 2005

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#108]
Schema snapshot fails on SQL 2005 instance. The problem seems to be creating snapshots of user defined table types that were not added until SQL 2008.

> 2022-03-21 15:35:26.830 +00:00 [ERR] Error creating schema snapshot AdventureWorksDW <18>
>    at DBADash.SchemaSnapshotDB.addUserDefinedTableType(Database db, DataTable dtSchema) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 881
>    at DBADash.SchemaSnapshotDB.SnapshotDB(String DBName) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 469
>    at DBADashService.SchemaSnapshotJob.Execute(IJobExecutionContext context) in D:\a\dba-dash\dba-dash\DBADashService\SchemaSnapshotJob.cs:line 62
> 

Options: 
- Skip this collection for SQL 2005.
- Disable schema snapshots for SQL 2005.

**Comment by DavidWiseman** [comment]
Fix will be included in the next release.
