### ISSUE TITLE
Community Tools execution error

### ISSUE THREAD

**Issue by dmartesi** [trimble-oss/dba-dash#1110]
I've installed 3.13.0 version and Community Tools.
DBAdash is running under service account 'dbadash', who is a Windows account and is part of sysadmin SQL Server Role.
If I click Execute button, I get this error:
---------------------------
Error Details
---------------------------
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot execute as the database principal because the principal "dbo" does not exist, this type of principal cannot be impersonated, or you do not have permission.

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)

   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)

   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)

   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)

   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location ---

   at DBADash.Messaging.MessageProcessing.SendMessageToService(Byte[] payload, Int32 agentID, Guid messageGroup, String connectionString, Int32 LifeTime) in D:\a\dba-dash\dba-dash\DBADash\Messaging\MessageProcessing.cs:line 289

   at DBADash.Messaging.MessageProcessing.SendMessageToService(Byte[] payload, Int32 agentID, Guid messageGroup, String connectionString, Int32 LifeTime) in D:\a\dba-dash\dba-dash\DBADash\Messaging\MessageProcessing.cs:line 289

   at DBADash.Messaging.MessageProcessing.SendMessageToService(Byte[] payload, Int32 agentID, Guid messageGroup, String connectionString, Int32 LifeTime) in D:\a\dba-dash\dba-dash\DBADash\Messaging\MessageProcessing.cs:line 289

   at DBADashGUI.Messaging.MessagingHelper.SendMessageAndProcessReply(MessageBase message, DBADashContext context, SetStatusDelegate setStatus, MessageCompletedDelegate processCompleted, Guid messageGroup) in D:\a\dba-dash\dba-dash\DBADashGUI\Messaging\MessagingHelper.cs:line 35

ClientConnectionId:39a7c44b-ea5b-4be0-aaf0-d0db405635b8

Error Number:15517,State:1,Class:16

**Comment by DavidWiseman** [comment]
You might need to change the database owner.  Does [this link](https://stackoverflow.com/questions/13823354/sql-server-principal-dbo-does-not-exist) help?  Have you tried running it from SSMS? You will likely have the same issue there.

**Comment by DavidWiseman** [comment]
Great - glad it's working.  Hope you find the new update useful!
