### ISSUE TITLE
Automatically disable WMI collection on RDS instances

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#113]
This error will occur:

> System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (0x800706BA)
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
>    at System.Management.ManagementScope.InitializeGuts(Object o)
>    at System.Management.ManagementScope.Initialize()
>    at System.Management.ManagementObjectSearcher.Initialize()
>    at System.Management.ManagementObjectSearcher.Get()
>    at DBADash.DBCollector.collectDrivesWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1378

As WMI collection will fail on RDS, this collection should automatically be disabled.

**Workaround:**

You can manually disable WMI collection for your RDS instances.  In the service configuration tool, click the "Source" tab.  Find the RDS instance in the existing connections and check the "No WMI" option.  Or check the "Don't use WMI" option in the "Other" tab when adding a new connection.

**Comment by DavidWiseman** [comment]
Issue fixed in the latest release
