### ISSUE TITLE
Slow Query capture not supported on RDS Express & Web editions

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#115]
This results in an error:

> 2022-03-30 20:24:07.350 +00:00 [ERR] Collect[Retrying] SlowQueries dev-rds.cyul2ukvtmod.eu-west-1.rds.amazonaws.com <12>Microsoft.Data.SqlClient.SqlException (0x80131904): Unable to create/alter extended events session: RDS for SQL Server supports extended events only for the Enterprise and Standard Editions
> Cannot alter the event session 'DBADash_1', because it does not exist or you do not have permission.
> Cannot alter the event session 'DBADash_1', because it does not exist or you do not have permission.
> Cannot alter the event session 'DBADash_1', because it does not exist or you do not have permission.
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()
>    at DBADash.DBCollector.collectSlowQueries() in C:\Git\TrimbleOSS\dba-dash\DBADash\DBCollector.cs:line 986
>    at DBADash.DBCollector.collect(CollectionType collectionType) in C:\Git\TrimbleOSS\dba-dash\DBADash\DBCollector.cs:line 850
>    at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
>    at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
>    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)

Desired behaviour - 
Better error handling for this specific error.  Log that it's not supported and disable the collection without retrying the collection.

**Comment by DavidWiseman** [comment]
Issue fixed in the latest release
