### ISSUE TITLE
Violation of PRIMARY KEY constraint on Drives data import

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#140]
### Discussed in https://github.com/trimble-oss/dba-dash/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **BrubiSQL** April 12, 2022</sup>
Hello,

I'm getting weird error on one of my SQL server instances, to be precise on the instance where I have placed DBA dash.
I have made a separate VM for DBA Dash testing, and on that VM I have only C drive, and I have installed SQL Server 2019 developer on it.
I have connected one more SQL instance to be monitored by DBA Dash, and on that instance, everything is working just fine.
My current working theory is, that issue is SQL Server placement on C drive.

Thank you for any help,
B.

---

Error is:
```
Message
Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__#AE2608F__737584F723D0E7AC'. Cannot insert duplicate key in object 'dbo.@Drives'. The duplicate key value is (C:\).
The data for table-valued parameter "@Drives" doesn't conform to the table type of the parameter. SQL Server error is: 3602, state: 30
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 377
   at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 219
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
ClientConnectionId:8ce1e050-afe1-4ee1-ac44-06a279b73519
Error Number:2627,State:2,Class:14
```

```
Message
Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__#AE2608F__737584F723D0E7AC'. Cannot insert duplicate key in object 'dbo.@Drives'. The duplicate key value is (C:\).
The data for table-valued parameter "@Drives" doesn't conform to the table type of the parameter. SQL Server error is: 3602, state: 30
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 377
   at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 219
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBImporter.Update() in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 218
ClientConnectionId:8ce1e050-afe1-4ee1-ac44-06a279b73519
Error Number:2627,State:2,Class:14
```</div>

**Comment by DavidWiseman** [comment]
As discussed, this error occurs because a DISTINCT is used which is over all columns.  If the free space or capacity (likely free space) we will end up with duplicate rows.  

The simplest fix is to use GROUP BY and AVG the free space and capacity columns.  MIN could be used instead to show a worst-case scenario.  The problem would be if the drive also expanded - though it's unlikely the query would capture a drive expansion in flight. A better option to show the worst case would be to de-duplicate using a ROW_NUMBER function and sort by free space.

Comparison:

````SQL
--original
SELECT DISTINCT dovs.volume_mount_point AS Name,
	dovs.total_bytes as Capacity,
	dovs.available_bytes as FreeSpace,
	dovs.logical_volume_name as Label
FROM sys.master_files mf
CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.file_id) dovs;

--avg
SELECT dovs.volume_mount_point AS Name,
	AVG(dovs.total_bytes) as Capacity,
	AVG(dovs.available_bytes) as FreeSpace,
	dovs.logical_volume_name as Label
FROM sys.master_files mf
CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.file_id) dovs
GROUP BY dovs.volume_mount_point,
		dovs.logical_volume_name;

-- row number de duplicate
WITH T AS (
	SELECT dovs.volume_mount_point AS Name,
		dovs.total_bytes as Capacity,
		dovs.available_bytes as FreeSpace,
		dovs.logical_volume_name as Label,
		ROW_NUMBER() OVER(PARTITION BY dovs.volume_mount_point ORDER BY dovs.available_bytes) rnum
	FROM sys.master_files mf
	CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.file_id) dovs
)
SELECT Name,
	Capacity,
	FreeSpace,
	Label
FROM T 
WHERE rnum=1
````

Performance is very similar between all 3 - this is a lab server with 1024 databases:
![image](https://user-images.githubusercontent.com/33157668/163461121-60534cbf-c907-472c-886f-be31f0f05cb9.png)

Interestingly the row number function has a higher estimated cost. With DISTINCT and with GROUP BY we are estimating to return far fewer rows.  The actual costs are about the same for all 3 - with the query taking around 2 seconds of CPU/duration.  This is on a lab server with 1024 databases.   On a server with 50 databases, the execution time is ~100ms.  
With the default settings, this query is run once per hour so query performance isn't a concern.  

The expectation is that there will be very small differences in free space in the duplicate rows.  The simplest solution using AVG should be sufficient.

**Comment by DavidWiseman** [comment]
Fix to be included in the next release

**Comment by DavidWiseman** [comment]
Fix is now in the latest release
