### ISSUE TITLE
Error on JobHistory Import

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#147]
Getting the following on one of the servers.  I believe this server has CDC enabled and the job just runs continuously.  I wonder if that is causing a problem with the query.  If you can pass me the query and which table it inserts/updates I can run it against this server to see if one of the values is out of line with the expected data type.

![image](https://user-images.githubusercontent.com/29784949/163589587-e1730bd0-1d44-49fb-8e9f-0d80b8f02054.png)

Microsoft.Data.SqlClient.SqlException (0x80131904): Arithmetic overflow error converting expression to data type int.
Warning: Null value is eliminated by an aggregate or other SET operation.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 377
   at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 219
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBImporter.Update() in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 218
ClientConnectionId:de177eaf-7634-442c-a8b3-46e015e83855
Error Number:8115,State:2,Class:16

**Comment by DavidWiseman** [comment]
This error is occurring on import.  The collection is JobHistory.  The stored proc to import is called [JobHistory_Upd](https://github.com/trimble-oss/dba-dash/blob/main/DBADashDB/dbo/Stored%20Procedures/JobHistory_Upd.sql).  The collection script is called [SQLJobHistory](https://github.com/trimble-oss/dba-dash/blob/main/DBADash/SQL/SQLJobHistory.sql)

The other collections follow the same naming pattern of appending "_Upd" to the collection name for the import stored proc.  Also, the collection queries are all in the same folder and they follow the naming pattern SQL{CollectionName}.sql.

Failed imports should be stored in the "Failed" folder where the DBA Dash agent is installed.  These are xml files.  I have a tool to make these easier to view.  It's available here (I might include it with DBA Dash in a later release)
https://github.com/DavidWiseman/SerializedDataSetViewer/releases/tag/Version_1.0
The tool allows you to see the collected data which can assist with troubleshooting.  It might not be necessary in this case - if the error always occurs you can just run the SQLJobHistory.sql query on your monitored instance.

**Comment by DavidWiseman** [comment]
I think you are right about CDC.  I've set this up in my lab and I'm running this query:
````SQL 
SELECT TOP(100) instance_id,
		jh.job_id,
		step_id,
		step_name,
		sql_message_id,
		sql_severity,
		message,
		run_status,
		run_date,
		run_time,
		run_duration,
		operator_id_emailed,
		operator_id_netsent,
		operator_id_paged,
		retries_attempted,
		server,
		j.name,
		STUFF(STUFF(RIGHT(REPLICATE('0', 6) +  CAST(jh.run_time as varchar(6)), 6), 3, 0, ':'), 6, 0, ':') 'run_time',
		STUFF(STUFF(STUFF(RIGHT(REPLICATE('0', 8) + CAST(jh.run_duration as varchar(8)), 8), 3, 0, ':'), 6, 0, ':'), 9, 0, ':') 'run_duration (DD:HH:MM:SS)  '
FROM msdb.dbo.sysjobhistory jh 
JOIN msdb.dbo.sysjobs j on jh.job_id = j.job_id
where name like 'cdc%'
````
![image](https://user-images.githubusercontent.com/33157668/163675025-a6a7e587-cc87-4c02-bf16-3c9a03a8232d.png)

It seems to be logging the current running time (86min) multiple times per minute- When these are summed up, we will end up with some impossible run durations that likely result in the overflow exception.  I'll need to do something different to handle this situation.  Until a fix is available you could disable the JobHistory collection for this instance to avoid the errors.

**Comment by DavidWiseman** [comment]
These executions report with a run status of 4 which is in progress:

0 = Failed
1 = Succeeded
2 = Retry
3 = Canceled
4 = In Progress

It probably doesn't make sense for DBA Dash to collect the in progress history rows - excluding run_status 4 could be a good fix for this issue.  If collected it at least wouldn't make sense to sum the durations for in progress rows.  
The best option is probably to exclude for now until there is a good use case for collection. It could also help keep reduce the size of the data that needs to be collected/stored.

**Comment by DavidWiseman** [comment]
Fix to exclude run_status 4 to be included in the next release.

**Comment by jacobgexigo** [comment]
Sounds great, thank you for finding it!

**Comment by DavidWiseman** [comment]
Fix is now in the latest release
