### ISSUE TITLE
Performance Tab - String or binary data would be truncated error

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#282]
Internal report via db monitoring channel:

```
************** Exception Text **************
Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DBADashGUI.CommonData.ObjectExecutionStats(Int32 instanceID, Int32 databaseID, Int64 objectID, Int32 dateGrouping, String measure, DateTime FromDate, DateTime ToDate, String instance) in D:\a\dba-dash\dba-dash\DBADashGUI\CommonData.cs:line 146
   at DBADashGUI.Performance.ObjectExecution.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\ObjectExecution.cs:line 107
   at DBADashGUI.Performance.ObjectExecution.RefreshData(Int32 instanceID, Int64 objectID, Int32 databaseID) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\ObjectExecution.cs:line 90
   at DBADashGUI.Performance.Performance.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Performance.cs:line 116
   at DBADashGUI.Main.LoadSelectedTab() in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 329
   at DBADashGUI.Main.Tabs_SelectedIndexChanged(Object sender, EventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 176
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
ClientConnectionId:3f47bb0a-91fe-4e36-b95b-45975aff6699
Error Number:8152,State:13,Class:16
```

**Comment by DavidWiseman** [comment]
#results table should change object_name column to NVARCHAR(257).  This combines schema name (nvarchar 128) + period char + object name (nvarchar 128).  128+1+128 = max length 257.
