### ISSUE TITLE
Availability Group collection errors

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#328]
When starting up a NULL value can be returned for resource_group_id in sys.availability_groups and for availability_mode in sys.availability_replicas.

> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'resource_group_id', table '@AvailabilityGroups'; column does not allow nulls. INSERT fails.
> The data for table-valued parameter "@AvailabilityGroups" doesn't conform to the table type of the parameter. SQL Server error is: 515, state: 2
> The statement has been terminated.
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at DBADash.DBImporter.update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 381
>    at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 223
>    at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
>    at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
>    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
>    at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
>    at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
>    at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
>    at DBADash.DBImporter.Update() in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 222
> ClientConnectionId:9c7ce70c-906c-436d-91d8-06d27e7d447a
> Error Number:515,State:2,Class:16

> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'availability_mode', table '@AvailabilityReplicas'; column does not allow nulls. INSERT fails.
> The data for table-valued parameter "@AvailabilityReplicas" doesn't conform to the table type of the parameter. SQL Server error is: 515, state: 2
> The statement has been terminated.
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at DBADash.DBImporter.update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 381
>    at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 223
>    at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
>    at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
>    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
> ClientConnectionId:9c7ce70c-906c-436d-91d8-06d27e7d447a
> Error Number:515,State:2,Class:16

**Comment by DavidWiseman** [comment]
Related to #274

**Comment by DavidWiseman** [comment]
sys.availability_groups - looks like all columns should be nullable except group_id

**Comment by DavidWiseman** [comment]
sys.availability_replicas - potentially all columns nullable?  Not well documented.  replica_id and group_id should probably be kept NOT NULL.

**Comment by DavidWiseman** [comment]
Fix included in 2.22.6 🚀
