### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#341]
Clicking around while testing and reviewing the latest current release (2.22.6) I got the following exception in the image.

How I got this:
- Using "Blocking:Instance" Chart I reviewed (randomly) one of the Blockings.
- Clicking the "BatchText" or "Text" links ends up to the Exception.

I suppose this error has somthing to do with the recent changes regarding the "Code Viewer" Window. BTW, the "Running Queries Viewer" Windows is also "On Top" which is not user friendly.

![cannot_access_disposed_object](https://user-images.githubusercontent.com/40255900/192596850-a51c095a-ad98-4fb8-b50e-e767f754f2e7.png)

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CodeViewer'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.Show(IWin32Window owner)
   at DBADashGUI.Common.ShowCodeViewer(String sql, String title, IWin32Window owner) in D:\a\dba-dash\dba-dash\DBADashGUI\Common.cs:line 447
   at DBADashGUI.Performance.RunningQueries.Dgv_CellContentClick(Object sender, DataGridViewCellEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\RunningQueries.cs:line 375
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by EsQueEl-Fella** [comment]
Also same Exception takes place in "Slow Queries". I skip the image here. Steps to reproduce:

- In "Slow Queries" select one of the links showing the number of the executed queries
- In the lower pan scroll to the end of the grid and click any of the links in the "Text" column.

**Comment by DavidWiseman** [comment]
This issue is triggered as the code viewer becomes a child of the blocking window and it gets disposed of once that window is closed.  I've added a check to create a new instance if it's disposed.  I've also changed it so it no longer has a parent window - this will fix the other issue mentioned in #336 and should ensure it doesn't get disposed of in the first place.

**Comment by DavidWiseman** [comment]
Fixed in 2.22.7 🎉
