### ISSUE TITLE
Error collecting plans for Running Queries

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#342]
> System.Exception: Error collecting plans for Running Queries
>  ---> System.Data.EvaluateException: Cannot find column [query_plan_hash].
>    at System.Data.NameNode.Bind(DataTable table, List`1 list)
>    at System.Data.BinaryNode.Bind(DataTable table, List`1 list)
>    at System.Data.DataExpression.Bind(DataTable table)
>    at System.Data.DataTable.Select(String filterExpression)
>    at DBADash.DBCollector.CollectPlans() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 573
>    at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 524
>    --- End of inner exception stack trace ---

This issue occurs on this line of code:
 ```c#
var nullRows = dt.Select("query_plan_hash IS NULL");
```

The query_plan_hash column is only added if rows are returned from the plan collection query.  Sometimes there will be no rows returned as the plans are no longer in the cache.

**Comment by DavidWiseman** [comment]
Fixed in 2.22.7 🎉
