### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#345]
This exception showed up in Version 2.2.27
Steps to reproduce:

- Start the DBADash GUI
- Select one of the server items in the navigation tree
- Switch to the Memory Tab
- Select one of the values in "Memory Clerk Type" Column.

This ONLY happens once and ONLY if we start the Application and follow the steps above. After the new start this exception doesn't show up anymore but then things start working really oddly. I will create a separate issue for that

![value_cannot_be_null](https://user-images.githubusercontent.com/40255900/192834536-07ddda6b-b6c9-44db-a26a-d0bdd5d193a3.png)

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary'2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary'2.Add(TKey key, TValue value)
   at DBADashGUI.Performance.MemoryUsage.showMemoryUsageForClerk(String format) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\MemoryUsage.cs:line 198
   at DBADashGUI.Performance.MemoryUsage.dgv_CellContentClick(Object sender, DataGridViewCellEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\MemoryUsage.cs:line 181
   at System.Windows.Forms.DataGridView.OnCellContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCommonCellContentClick(Int32 columnIndex, Int32 rowIndex, Boolean doubleClick)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidWiseman** [comment]
This issue is fixed in 2.22.8.  🎉

Thank you for including detailed instructions to reproduce the issue.
