### ISSUE TITLE
Error When Refreshing Snapshot Summary

### ISSUE THREAD

**Issue by jacobgexigo** [trimble-oss/dba-dash#447]
Version 2.26.0

The Snapshot Summary is blank on my Checks (both at the top level, the server level and the database level) and when I click the refresh button for it, I get an unhandled exception. 

![image](https://user-images.githubusercontent.com/29784949/204127115-21de273a-5a2c-40e0-a647-f038914386aa.png)

************** Exception Text **************
System.ArgumentNullException: Value cannot be null. (Parameter 'values')
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at DBADashGUI.Changes.SchemaSnapshots.DdlSnapshotInstanceSummary() in D:\a\dba-dash\dba-dash\DBADashGUI\SchemaCompare\SchemaSnapshots.cs:line 108
   at DBADashGUI.Changes.SchemaSnapshots.LoadInstanceSummary() in D:\a\dba-dash\dba-dash\DBADashGUI\SchemaCompare\SchemaSnapshots.cs:line 121
   at DBADashGUI.Changes.SchemaSnapshots.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\SchemaCompare\SchemaSnapshots.cs:line 97
   at DBADashGUI.Changes.SchemaSnapshots.TsRefresh_Click(Object sender, EventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\SchemaCompare\SchemaSnapshots.cs:line 281
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidWiseman** [comment]
Thank you for reporting this.  I don't get this issue but the exception text should help me identify the problem.

**Comment by DavidWiseman** [comment]
Please let me know if you still get this error in 2.27.0.  I'm not sure if this will be fixed but there have been some code changes that might impact this bug.  If you still get the error, please post the exception text again as this will have changed.

**Comment by DavidWiseman** [comment]
Please reopen if this issue still occurs on the latest release.
