### ISSUE TITLE
Error in WMI GetProcessorName

### ISSUE THREAD

**Issue by dmartesi** [trimble-oss/dba-dash#566]
Hi, yesterday I've upgraded to version 2.36.1 and now I have a new error in DBA Dash Errorlog:

Microsoft.Management.Infrastructure.CimException: Access denied 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Management.Infrastructure.CimSession.InvokeMethod(String namespaceName, CimInstance instance, String methodName, CimMethodParametersCollection methodParameters, CimOperationOptions options)
   at Microsoft.Management.Infrastructure.CimSession.InvokeMethod(String namespaceName, CimInstance instance, String methodName, CimMethodParametersCollection methodParameters)
   at Microsoft.Management.Infrastructure.CimSession.InvokeMethod(CimInstance instance, String methodName, CimMethodParametersCollection methodParameters)
   at DBADash.DBCollector.GetProcessorName() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1386
   at DBADash.DBCollector.CollectProcessorWMI() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1368

Am I missing something?

Thanks

**Comment by dmartesi** [comment]
I already used WMI with no errors, until I get updated to 2.36.1
If dbadash service account already collected other WMI data, I think this is not a permission issue...

Let me know if I can help you with other debug information.
If there's no other solution, I can disable WMI or ignore the error.
