### ISSUE TITLE
Timeout during collection

### ISSUE THREAD

**Issue by dennisa72295** [trimble-oss/dba-dash#614]
I keep getting a DBA Dash Error on one or more of my databases.  What can I do to fix this?
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DBADash.DBCollector.GetDT(String tableName, String SQL, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1090
   at DBADash.DBCollector.AddDT(String tableName, String sql, Int32 commandTimeout, SqlParameter[] param) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 1099
   at DBADash.DBCollector.ExecuteCollection(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 908
   at DBADash.DBCollector.<>c__DisplayClass58_0.<Collect>b__0(Context _) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 478
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 474
ClientConnectionId:3aaa9886-3c8d-4844-951c-de77d776bfb3
Error Number:-2,State:0,Class:11

**Comment by DavidWiseman** [comment]
Which collection is timing out? If you got this error from the "DBA Dash ErrorLog" tab in the GUI, this is the "Source" tab in the grid.  If it's from the error log you should find this information just above the error.

Once you have the collection, you should be able to find the associated query [here](
https://github.com/DavidWiseman/dba-dash/tree/main/DBADash/SQL).

You could try running the query in SSMS to get an idea of how long the query will take normally.  It's possible to [adjust the query timeout](https://dbadash.com/docs/help/query-timeout/).  You can also [adjust the schedule](https://dbadash.com/docs/help/schedule/) to run less frequently or disable the collection.  If you are able to identify a fix to improve the performance of the collection, you can also submit a pull request to improve the performance of the collection. Or post back here with your findings.

The default query timeouts should work for most environments but some users will run into issues.  e.g. If you have a very large number of databases some of the per-database collections like the [Identity Columns](https://github.com/DavidWiseman/dba-dash/blob/main/DBADash/SQL/SQLIdentityColumns.sql) collection might have issues.  That collection might also have issues if you have a very large number of tables.  

Hope this helps,

David

**Comment by dennisa72295** [comment]
The Source is CPU.  I grabbed the SQLCPU.sql file and tried to run it in SSMS as is but because of the variable not being defined I wasn't able to run it stand alone.  Where do I adjust the query timeout?

**Comment by DavidWiseman** [comment]
See here:
https://dbadash.com/docs/help/query-timeout/

You can add `DECLARE @TOP INT = 60;` to run the query:

```sql
DECLARE @TOP INT = 60;
IF OBJECT_ID('sys.dm_db_resource_stats') IS NOT NULL
BEGIN
	SELECT TOP(@TOP) end_time AS EventTime,
		CAST(avg_cpu_percent AS INT),
		100-CAST(avg_cpu_percent AS INT) AS SystemIdle
	FROM sys.dm_db_resource_stats
END
ELSE
BEGIN
	DECLARE @ts_now bigint 
	SELECT @ts_now= cpu_ticks/(cpu_ticks/ms_ticks) 
	FROM sys.dm_os_sys_info; 
 
	SELECT TOP(@TOP) DATEADD(ms, -1 * (@ts_now - [timestamp]), GETUTCDATE()) AS [EventTime],
					SQLProcessUtilization AS [SQLProcessCPU], 
				   SystemIdle AS [SystemIdleProcess] 
	FROM (SELECT record.value('(./Record/@id)[1]', 'int') AS record_id, 
				record.value('(./Record//SystemHealth/SystemIdle)[1]', 'int') 
				AS [SystemIdle], 
				record.value('(./Record//SystemHealth/ProcessUtilization)[1]', 'int') 
				AS [SQLProcessUtilization], [timestamp] 
		  FROM (SELECT [timestamp], CONVERT(xml, record) AS [record] 
				FROM sys.dm_os_ring_buffers WITH (NOLOCK)
				WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR' 
				AND record LIKE N'%<SystemHealth>%') AS x) AS y 
	ORDER BY record_id DESC OPTION (RECOMPILE);
END
```

**Comment by dennisa72295** [comment]
The query runs fine in SSMS. I tried adjusting the timeouts in the commandTimeouts.json file by adjusting the default timeout.  Now I'm seeing more timeouts with sources like ObjectExecutionStats, JobHistory, PerformanceCounters, SeesionWaits, etc.  Almost all have an Error Context of Import[Retrying] or Import

**Comment by DavidWiseman** [comment]
If the context is import the timeout is pushing the data into the repository database rather than collecting the data.  The timeout is 60 seconds for importing the data which isn't currently configurable.  It should be enough time though and might suggest some issues with the instance where the repository DB is located.  I'd start by checking the wait stats on that instance for the time period where you are experiencing the timeouts.

**Comment by DavidWiseman** [comment]
Import timeout is [now configurable](https://dbadash.com/docs/help/query-timeout/#additional-timeouts) if needed.
