### ISSUE TITLE
Running Query Plan collection issue

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#619]
System.Exception: Error collecting plans for Running Queries
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at DBADash.DBCollector.<GetPlansList>b__65_2(IGrouping`2 g) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 677
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at DBADash.DBCollector.GetPlansList() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 670
   at DBADash.DBCollector.GetPlansSQL() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 616
   at DBADash.DBCollector.CollectPlans() in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 530
   at DBADash.DBCollector.Collect(CollectionType collectionType) in D:\a\dba-dash\dba-dash\DBADash\DBCollector.cs:line 501
   --- End of inner exception stack trace ---

Issue in this case is summing up CPU time - it's possible to overflow int value.  Might also be worth changing the granted_query_memory to use ToInt64

where g.Sum(r => Convert.ToInt32(r["cpu_time"])) >= Source.PlanCollectionCPUThreshold || g.Sum(r => Convert.ToInt32(r["granted_query_memory"])) >= Source.PlanCollectionMemoryGrantThreshold || g.Count() >= Source.PlanCollectionCountThreshold || g.Max(r => ((DateTime)r["SnapshotDateUTC"]).Subtract((DateTime)r["last_request_start_time_utc"])).TotalMilliseconds >= Source.PlanCollectionDurationThreshold

**Comment by DavidWiseman** [comment]
Fixed in 2.40.2 🎉
