### ISSUE TITLE
Humanizer issue for non english language installs

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#627]
### Discussed in https://github.com/trimble-oss/dba-dash/discussions/626

<div type='discussions-op-text'>

<sup>Originally posted by **teslyuk70** May 31, 2023</sup>
Error Message:
System.ArgumentException: The resource object with key 'TimeSpanHumanize_MultipleHours' was not found (Parameter 'resourceKey')
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 137
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForTimeSpan(TimeUnit unit, Int32 count, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 102
   at Humanizer.Localisation.Formatters.DefaultFormatter.TimeSpanHumanize(TimeUnit timeUnit, Int32 unit, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 71
   at Humanizer.TimeSpanHumanizeExtensions.CreateTheTimePartsWithUpperAndLowerLimits(TimeSpan timespan, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 63
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, Boolean countEmptyUnits, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 50
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 33
   at DBADashGUI.Performance.Waits.<>c.<CalcTopWaits>b__32_4(<>f__AnonymousType0`5 x) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Waits.cs:line 148
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DBADashGUI.Performance.Waits.CalcTopWaits(DataTable& dt) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Waits.cs:line 147
   at DBADashGUI.Performance.Waits.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Waits.cs:line 173
   at DBADashGUI.Performance.Waits.RefreshData(Int32 instanceID) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Waits.cs:line 92
   at DBADashGUI.Performance.Performance.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Performance.cs:line 57
   at DBADashGUI.Performance.Performance.SetContext(DBADashContext context) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\Performance.cs:line 40
   at DBADashGUI.Main.LoadSelectedTab() in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 329
   at DBADashGUI.Main.Instance_Selected(Object sender, InstanceSelectedEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 1213
   at DBADashGUI.Performance.PerformanceSummary.Dgv_CellContentClick(Object sender, DataGridViewCellEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Performance\PerformanceSummary.cs:line 384
   at System.Windows.Forms.DataGridView.OnCellContentClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCommonCellContentClick(Int32 columnIndex, Int32 rowIndex, Boolean doubleClick)
   at System.Windows.Forms.DataGridViewCell.OnMouseUpInternal(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellMouseUp(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

What can I do with this error? I have local on server ru-RU.
</div>

**Comment by DavidWiseman** [comment]
Similar:
https://github.com/Humanizr/Humanizer/issues/690
Note: Currently using Humanizer.Core so could switch to Humanizer.  Or could specify culture.

**Comment by DavidWiseman** [comment]
Fixed in 2.41.0 🚀
