### ISSUE TITLE
Cannot insert the value NULL into column 'last_value', table 'DBADashDB.dbo.IdentityColumnsHistory'

### ISSUE THREAD

**Issue by EsQueEl-Fella** [trimble-oss/dba-dash#670]
Hi,

DBADash Version: 2.41.0.0

Please have a look at the image / exception. I got this exception on 2 Different Servers at 00:00:00
Thanks and Best Regards.

![grafik](https://github.com/trimble-oss/dba-dash/assets/40255900/88623597-3138-4799-ad10-616e0265e69c)

Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'last_value', table 'DBADashDB.dbo.IdentityColumnsHistory'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.Update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 401
   at DBADash.DBImporter.<>c__DisplayClass11_1.<Update>b__5(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 250
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
ClientConnectionId:94f170ee-32ff-4843-a034-52d5fb2cf82c
Error Number:515,State:2,Class:16

**Comment by DavidWiseman** [comment]
Thank you for reporting this.  This will be fixed in the next release.

**Comment by DavidWiseman** [comment]
Fixed in 2.45.0 🚀
