### ISSUE TITLE
Sorting by Hidden column in Summary tab throws an error

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#673]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Cannot find column colHidden.
   at System.Data.DataTable.ParseSortString(String sortString)
   at System.Data.DataView.CheckSort(String sort)
   at System.Data.DataView.set_Sort(String value)
   at DBADashGUI.Summary.DgvSummary_ColumnHeaderMouseClick(Object sender, DataGridViewCellMouseEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Checks\Summary.cs:line 470
   at System.Windows.Forms.DataGridView.OnColumnHeaderMouseClick(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by DavidWiseman** [comment]
Fixed in 2.45.0 🚀
