### ISSUE TITLE
Error saving timezones or switching themes after changing timezone

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#704]
To reproduce:

Change timezone and click "Save Timezone Preference"

Or

Change timezone and then change theme

![image](https://github.com/trimble-oss/dba-dash/assets/33157668/53e8d09b-e2b4-451a-b6c2-8e3f567d65ab)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: No mapping exists from object type System.TimeZoneInfo to a known managed provider native type.
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at Microsoft.Data.SqlClient.SqlCommand.SetUpRPCParameters(_SqlRPC rpc, Boolean inSchema, SqlParameterCollection parameters)
   at Microsoft.Data.SqlClient.SqlCommand.BuildRPC(Boolean inSchema, SqlParameterCollection parameters, _SqlRPC& rpc)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADashGUI.DBADashUser.Update() in D:\a\dba-dash\dba-dash\DBADashGUI\DBADashUser.cs:line 38
   at DBADashGUI.Main.SetTheme(BaseTheme theme) in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 1992
   at DBADashGUI.Main.LightToolStripMenuItem_Click(Object sender, EventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 1979
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Private.CoreLib.dll
----------------------------------------
DBADash
    Assembly Version: 2.47.0.0
    Win32 Version: 2.47.0.0
    CodeBase: file:///C:/DBADash/DBADash.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.dll
----------------------------------------
DBADashSharedGUI
    Assembly Version: 2.47.0.0
    Win32 Version: 2.47.0.0
    CodeBase: file:///C:/DBADash/DBADashSharedGUI.dll
----------------------------------------
CommandLine
    Assembly Version: 2.9.1.0
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/DBADash/CommandLine.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/netstandard.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/System.Windows.Forms.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Console.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Threading.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Linq.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Collections.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Diagnostics.TraceSource.dll
----------------------------------------
PresentationFramework
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/System.Xaml.dll
----------------------------------------
DirectWriteForwarder
    Assembly Version: 6.0.2.0
    Win32 Version: 6,0,2223,42502 @Commit: f501934867fd4723518c1c7b03c6033c2e52ecad
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Diagnostics.Debug.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Collections.NonGeneric.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/runtimes/win/lib/net6.0/System.Drawing.Common.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2223.42407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/Accessibility.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/WindowsFormsIntegration.dll
----------------------------------------
DiffPlex.Wpf
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/DBADash/DiffPlex.Wpf.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/Microsoft.Win32.Registry.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Private.Uri.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Net.WebClient.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Net.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Memory.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.ComponentModel.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/UIAutomationTypes.dll
----------------------------------------
System.IO.Packaging
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/System.IO.Packaging.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.ObjectModel.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Numerics.Vectors.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Threading.ThreadPool.dll
----------------------------------------
DiffPlex.Wpf.resources
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/DBADash/en/DiffPlex.Wpf.resources.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/runtimes/win/lib/net6.0/System.Windows.Extensions.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Collections.Concurrent.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/PresentationFramework.Aero2.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/UIAutomationProvider.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/runtimes/win/lib/net6.0/Microsoft.Win32.SystemEvents.dll
----------------------------------------
ICSharpCode.AvalonEdit
    Assembly Version: 6.3.0.90
    Win32 Version: 6.3.0.90
    CodeBase: file:///C:/DBADash/ICSharpCode.AvalonEdit.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Net.Requests.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/System.Drawing.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.Loader.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.Serialization.Formatters.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/mscorlib.dll
----------------------------------------
LiveCharts.WinForms
    Assembly Version: 0.9.7.1
    Win32 Version: 0.9.7.1
    CodeBase: file:///C:/DBADash/LiveCharts.WinForms.dll
----------------------------------------
LiveCharts.Wpf
    Assembly Version: 0.9.7.0
    Win32 Version: 0.9.7
    CodeBase: file:///C:/DBADash/LiveCharts.Wpf.dll
----------------------------------------
LiveCharts
    Assembly Version: 0.9.7.0
    Win32 Version: 0.9.7
    CodeBase: file:///C:/DBADash/LiveCharts.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.dll
----------------------------------------
DiffPlex
    Assembly Version: 1.7.1.0
    Win32 Version: 1.7.1.0
    CodeBase: file:///C:/DBADash/DiffPlex.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1938.49
    Win32 Version: 1.0.1938.49
    CodeBase: file:///C:/DBADash/Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1938.49
    Win32 Version: 1.0.1938.49
    CodeBase: file:///C:/DBADash/Microsoft.Web.WebView2.Core.dll
----------------------------------------
DBADashTools
    Assembly Version: 2.47.0.0
    Win32 Version: 2.47.0.0
    CodeBase: file:///C:/DBADash/DBADashTools.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Xml.XmlSerializer.dll
----------------------------------------
Microsoft.SqlServer.ConnectionInfo
    Assembly Version: 17.100.0.0
    Win32 Version: 17.100.18.0
    CodeBase: file:///C:/DBADash/Microsoft.SqlServer.ConnectionInfo.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/DBADash/Newtonsoft.Json.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Data.Common.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Private.CoreLib.dll
----------------------------------------
System.Security.Cryptography.ProtectedData
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/DBADash/System.Security.Cryptography.ProtectedData.dll
----------------------------------------
Microsoft.Data.SqlClient
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/DBADash/runtimes/win/lib/net6.0/Microsoft.Data.SqlClient.dll
----------------------------------------
System.Transactions.Local
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Transactions.Local.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.423.11508
    CodeBase: file:///C:/DBADash/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Security.Claims.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.55.0.0
    Win32 Version: 4.55.0.0
    CodeBase: file:///C:/DBADash/Microsoft.Identity.Client.dll
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Text.Encoding.CodePages.dll
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/DBADash/runtimes/win/lib/net6.0/System.Runtime.Caching.dll
----------------------------------------
Microsoft.SqlServer.Server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/DBADash/Microsoft.SqlServer.Server.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.723.27404
    CodeBase: file:///C:/DBADash/System.Text.Json.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2223.42502
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.22/PresentationFramework-SystemData.dll
----------------------------------------
Humanizer
    Assembly Version: 2.14.0.0
    Win32 Version: 2.14.1.48190
    CodeBase: file:///C:/DBADash/Humanizer.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2223.42425
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.22/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

```

**Comment by DavidWiseman** [comment]
Fixed in 2.47.1
