### ISSUE TITLE
Running Jobs DBNull error

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#719]
System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.Int32'.
   at DBADashGUI.AgentJobs.RunningJobs.DgvRunningJobs_RowsAdded(Object sender, DataGridViewRowsAddedEventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\AgentJobs\RunningJobs.cs:line 118
   at System.Windows.Forms.DataGridView.OnRowsAdded(DataGridViewRowsAddedEventArgs e)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   at System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   at System.Windows.Forms.DataGridViewRowCollection.AddInternal(DataGridViewRow dataGridViewRow)
   at System.Windows.Forms.DataGridView.RefreshRows(Boolean scrollIntoView)
   at System.Windows.Forms.DataGridView.RefreshColumnsAndRows()
   at System.Windows.Forms.DataGridView.OnDataSourceChanged(EventArgs e)
   at System.Windows.Forms.DataGridView.set_DataSource(Object value)
   at DBADashGUI.AgentJobs.RunningJobs.RefreshData() in D:\a\dba-dash\dba-dash\DBADashGUI\AgentJobs\RunningJobs.cs:line 66
   at DBADashGUI.AgentJobs.RunningJobs.SetContext(DBADashContext context) in D:\a\dba-dash\dba-dash\DBADashGUI\AgentJobs\RunningJobs.cs:line 89
   at DBADashGUI.Main.LoadSelectedTab() in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 346
   at DBADashGUI.Main.Tabs_SelectedIndexChanged(Object sender, EventArgs e) in D:\a\dba-dash\dba-dash\DBADashGUI\Main.cs:line 310
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidWiseman** [comment]
Fixed in 2.48.1
