### ISSUE TITLE
Schema snapshots can fail due to errors scripting synonyms

### ISSUE THREAD

**Issue by DavidWiseman** [trimble-oss/dba-dash#915]
A synonym that references a table in a log shipped database might throw an error when scripting via SMO if the database is in a restoring state.  This will result in the snapshot failing totally.  It would be better to skip and continue processing.  The value of including synonyms in the schema snapshot is probably limited in most cases.  

```
Microsoft.SqlServer.Management.Smo.FailedOperationException: Script failed for Synonym '<NAME_OF_SYNONYM>'. 
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Database 'NAME_OF_DATABASE' cannot be opened. It is in the middle of a restore.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.SqlServer.Management.Smo.DataProvider.ReadInternal()
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetInitDataReader(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitializeKeepDirtyValues()
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreateObjects(IEnumerable`1 urns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptUrns(List`1 orderedUrns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptWorker(List`1 urns, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(DependencyCollection depList, SqlSmoObject[] objects, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithListWorker(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
ClientConnectionId:27d09d08-afed-49a2-9651-1f7f06ecc67e
Error Number:927,State:6,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[] objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.Script(Urn[] urns, SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.Scripter.Script(SqlSmoObject sqlSmoObject)
   at DBADash.SchemaSnapshotDB.AddSynonyms(Database db, DataTable dtSchema) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 675
   at DBADash.SchemaSnapshotDB.SnapshotDB(String DBName) in D:\a\dba-dash\dba-dash\DBADash\SchemaSnapshotDB.cs:line 322
   at DBADashService.SchemaSnapshotJob.Execute(IJobExecutionContext context) in D:\a\dba-dash\dba-dash\DBADashService\SchemaSnapshotJob.cs:line 62
```

As a workaround, the object type can be removed from the config.

**Comment by DavidWiseman** [comment]
Included in 3.6 🎉
