### ISSUE TITLE
System.Exception: DDLSnapshot:DBName. Primary key violation. This can occur if you have a case sensitive database collation that ...

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#92]
I'm guessing this is for the schema snapshots.  Yes, the database uses a case sensitive collation

Message
System.Exception: DDLSnapshot:DBName. Primary key violation.  This can occur if you have a case sensitive database collation that contains tables, SPs or other database objects with names that are no longer unique with a case insensitive comparison.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__#AEA38EE__CDB0B3FC1F8058C3'. Cannot insert duplicate key in object 'dbo.@ss'. The duplicate key value is (budaarontest, dbo, U  ).
The data for table-valued parameter "@ss" doesn't conform to the table type of the parameter. SQL Server error is: 3602, state: 30
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.updateSnapshot(String tableName, String databaseName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 311
ClientConnectionId:60b88a6e-e248-4394-8fdd-d0c5b3ebc11e
Error Number:2627,State:2,Class:14
   --- End of inner exception stack trace ---
   at DBADash.DBImporter.updateSnapshot(String tableName, String databaseName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 317
   at DBADash.DBImporter.<>c__DisplayClass11_3.<Update>b__7(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 237
   at Polly.Policy.<>c__DisplayClass110_0.<Execute>b__0(Context ctx, CancellationToken _)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at DBADash.DBImporter.Update() in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 236

**Comment by DavidWiseman** [comment]
Hi,

The combination of Object Name,  Schema Name, and Object Type must be unique.  Your duplicate is:  
budaarontest, dbo, U

So I'm guessing you have another table with the same name somewhere but with different casing. e.g.
budaarontest
BudaaronTest

This will cause problems for the schema snapshot.  If you have a case-sensitive database the schema snapshot will work OK as long as you keep the object names unique when case is ignored.  Having two objects with the same name that differ only by case is likely to cause some confusion, so I recommend changing the object names if possible.  

Another option to work around this issue is to exclude this particular database from the schema snapshots.  You can specify a comma-separated list of DBs you do want to snapshot.  You can also exclude certain databases by using -.  e.g.

*,-ExcludeThisDatabase
or
IncludeMe1,IncludeMe2

Hope this helps,

David
