### ISSUE TITLE
Install Service error when connecting as .\user - The account name is invalid or does not exist

### ISSUE THREAD

**Issue by vcmcstech** [trimble-oss/dba-dash#95]
Tried installing service with user prompt
Entered .\user to set a local user
Saw prompt that said domain was not specified, click yes to use local domain
Install errored

Works ok if i specify Hostname\user for user

Installing service DBADashService...

An exception occurred during the Install phase.
System.ComponentModel.Win32Exception: The account name is invalid or does not exist, or the password is invalid for the account name specified.

The Rollback phase of the installation is beginning.

The Rollback phase completed successfully.

The transacted install has completed.
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.InvalidOperationException: The installation failed, and the rollback has been performed.
 ---> System.ComponentModel.Win32Exception (1057): The account name is invalid or does not exist, or the password is invalid for the account name specified.
   at System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at Topshelf.Runtime.Windows.HostInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   --- End of inner exception stack trace ---
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   at Topshelf.Runtime.Windows.HostServiceInstaller.InstallService(Action`1 beforeInstall, Action`1 afterInstall, Action`1 beforeRollback, Action`1 afterRollback)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.InstallService(InstallHostSettings settings, Action`1 beforeInstall, Action afterInstall, Action beforeRollback, Action afterRollback)
   at Topshelf.Hosts.InstallHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

**Comment by DavidWiseman** [comment]
Hi,

Usually you would want to use a domain user account for DBA Dash as this would allow it to connect to SQL instances on the domain that you have provisioned access to.  If DBA Dash is running on a workstation to collect from the local instance - a local user could be used.  You could also use a local user and use SQL authentication to connect to other SQL instances on the domain.  If you use SQL authentication, the credentials need to be stored in the ServiceConfig.json file which isn't as secure as Windows authentication.  The password is encrypted in the json file, but the key storage for the encryption is not secure - consider as obfuscation rather than encryption.

I think this issue might be resolved with some improvements to the documentation.

Thanks

**Comment by vcmcstech** [comment]
Domain user isn't required.  It works ok if i specify Hostname\user for the
local user.

I think the problem is the update to include domain in the username, it
prolly tries to add Hostname\  in front of .\user

also note, if i set Hostname\user here the service shows logon user as
.\user after install

**Comment by DavidWiseman** [comment]
A fix for this will be included in the next release

**Comment by DavidWiseman** [comment]
This issue is fixed in the latest release now.
