### ISSUE TITLE
OS Errors for AWS EC2

### ISSUE THREAD

**Issue by aachaemenes** [trimble-oss/dba-dash#952]
Getting this error 

Microsoft.Data.SqlClient.SqlException (0x80131904): Operand type clash: datetime2 is incompatible with int
The data for table-valued parameter "@OSInfo" doesn't conform to the table type of the parameter. SQL Server error is: 200, state: 7
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DBADash.DBImporter.Update(String tableName) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 513
   at DBADash.DBImporter.<>c__DisplayClass17_0.<TryUpdate>b__0(Context context) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 463
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Implementation(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute(Action`1 action, Context context)
   at DBADash.DBImporter.TryUpdate(String tableName, List`1& exceptions) in D:\a\dba-dash\dba-dash\DBADash\DBImporter.cs:line 462
ClientConnectionId:fb440ac4-3ae9-48bc-8db7-358f65e4ea0d
Error Number:206,State:2,Class:16

**Comment by DavidWiseman** [comment]
This seems odd.  What version of DBA Dash are you using?

**Comment by aachaemenes** [comment]
Latest version.

**Comment by DavidWiseman** [comment]
Do you get this error on all your monitored instances?  What SQL version is the monitored instance that is having the issue?  What SQL version is the repository database?

Can you run [this query](https://raw.githubusercontent.com/trimble-oss/dba-dash/main/DBADash/SQL/SQLOSInfo.sql) on the monitored instance and post a screenshot of the results?

If you open the service configuration tool and click the "deploy/update database" button then click "deploy" it will re-apply the dacpac - ensuring your repository DB matches the expected schema.

![image](https://github.com/user-attachments/assets/3bfc928c-9c17-4905-a8e8-98e95301485f)

Hope this helps.

**Comment by aachaemenes** [comment]
Deploy fixed the issue. thanks.
